# mepauth deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mepauth-deploy
  namespace: mep
  labels:
    app: mepauth-deploy
spec:
  selector:
    matchLabels:
      app: mepauth-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: mepauth-deploy
    spec:
      containers:
        - image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mepauth:latest
          imagePullPolicy: IfNotPresent
          name: mepauth
          tty: true
          args: ['sh']
          ports:
            - containerPort: 10443
          env:
            - name: MEPAUTH_APIGW_HOST
              value: kong-service
            - name: MEPAUTH_APIGW_PORT
              value: "8444"
            - name: MEPAUTH_CERT_DOMAIN_NAME
              value: edgegallery
          volumeMounts:
            - name: mepauth-certs
              mountPath: /usr/mep/ssl/
              readOnly: true
            - name: mepauth-jwt
              mountPath: /usr/mep/keys/
              readOnly: true
          volumeMounts:
            - name: mepauth-properties
              mountPath: /usr/mep/mprop/
              readOnly: true
      volumes:
        - name: mepauth-certs
          secret:
            secretName: mepauth-secret
            items:
              - key: server.crt
                path: server.crt
                mode: 0644
              - key: server.key
                path: server.key
                mode: 0644
              - key: ca.crt
                path: ca.crt
                mode: 0644
        - name: mepauth-jwt
          secret:
            secretName: mepauth-secret
            items:
              - key: jwt_publickey
                path: jwt_publickey
                mode: 0644
              - key: jwt_encrypted_privatekey
                path: jwt_encrypted_privatekey
                mode: 0644
        - name: mepauth-properties
          secret:
            secretName: mepauth-secret
            items:
              - key: mepauth.properties
                path: mepauth.properties
                mode: 0644

# mepauth servcie
---
apiVersion: v1
kind: Service
metadata:
  name: mepauth-service
  namespace: mep
spec:
  selector:
    app: mepauth-deploy
  type: NodePort
  ports:
    - port: 10443
